import { Language } from './types';

export const SUPPORTED_FORMATS = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg', 'application/pdf'];

export const INITIAL_SETTINGS = {
  convertToPdf: true,
  saveSeparately: false,
  saveInGroup: false,
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    selectAll: "Selecionar todos",
    clearAll: "Limpar todos",
    convertToPdf: "Converter para PDF",
    saveSeparately: "Salvar separado",
    saveInGroup: "Salvar em grupo",
    save: "Salvar",
    saving: "Salvando...",
    total: "Total",
    dragDrop: "Arraste ou adicione",
    dropHere: "Solte os arquivos",
    addFiles: "Adicionar arquivos",
    edit: "Editar",
    editorTitle: "Editor de Imagem",
    pdfEditorTitle: "Editor de PDF",
    undo: "Desfazer",
    redo: "Refazer",
    reset: "Restaurar",
    cancel: "Cancelar",
    confirm: "Confirmar Edição",
    removeBg: "Remover Fundo",
    enhance: "Melhorar Nitidez",
    manualCrop: "Recorte Manual",
    cropInstructions: "Selecione uma área na imagem. O recorte será aplicado automaticamente ao soltar o mouse.",
    processing: "Processando...",
    aiTools: "Ferramentas IA",
    language: "Português do Brasil",
    theme: "Tema",
    deleteDoc: "Excluir documento",
    search: "Visualizar",
    rotate: "Girar",
    page: "Página",
    savePdf: "Salvar PDF",
    loadingPdf: "Carregando PDF...",
    docSaved: "Documento(s) Salvo(s)",
    docSaveError: "Erro ao salvar documento(s)",
    openFolder: "Exibir pasta de destino",
    folderInfo: "Os arquivos foram salvos na sua pasta padrão de Downloads.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas com sucesso",
    sortError: "Erro ao ordenar páginas"
  },
  'en': {
    selectAll: "Select All",
    clearAll: "Clear All",
    convertToPdf: "Convert to PDF",
    saveSeparately: "Save Separately",
    saveInGroup: "Save as Group",
    save: "Save",
    saving: "Saving...",
    total: "Total",
    dragDrop: "Drag or add",
    dropHere: "Drop files here",
    addFiles: "Add files",
    edit: "Edit",
    editorTitle: "Image Editor",
    pdfEditorTitle: "PDF Editor",
    undo: "Undo",
    redo: "Redo",
    reset: "Reset",
    cancel: "Cancel",
    confirm: "Confirm Edit",
    removeBg: "Remove Background",
    enhance: "Enhance Sharpness",
    manualCrop: "Manual Crop",
    cropInstructions: "Select an area on the image. Cropping applies automatically on release.",
    processing: "Processing...",
    aiTools: "AI Tools",
    language: "English",
    theme: "Theme",
    deleteDoc: "Delete document",
    search: "Preview",
    rotate: "Rotate",
    page: "Page",
    savePdf: "Save PDF",
    loadingPdf: "Loading PDF...",
    docSaved: "Document(s) Saved",
    docSaveError: "Error saving document(s)",
    openFolder: "Show destination folder",
    folderInfo: "Files are saved to your default Downloads folder.",
    autoSort: "Auto Sort",
    sorting: "Sorting...",
    sortSuccess: "Pages sorted successfully",
    sortError: "Error sorting pages"
  },
  'es': {
    selectAll: "Seleccionar todos",
    clearAll: "Limpiar todo",
    convertToPdf: "Convertir a PDF",
    saveSeparately: "Guardar por separado",
    saveInGroup: "Guardar en grupo",
    save: "Guardar",
    saving: "Guardando...",
    total: "Total",
    dragDrop: "Arrastra o agrega",
    dropHere: "Suelta los archivos",
    addFiles: "Agregar archivos",
    edit: "Editar",
    editorTitle: "Editor de Imagen",
    pdfEditorTitle: "Editor de PDF",
    undo: "Deshacer",
    redo: "Rehacer",
    reset: "Restaurar",
    cancel: "Cancelar",
    confirm: "Confirmar Edición",
    removeBg: "Eliminar Fondo",
    enhance: "Mejorar Nitidez",
    manualCrop: "Recorte Manual",
    cropInstructions: "Seleccione un área. El recorte se aplica automáticamente al soltar.",
    processing: "Procesando...",
    aiTools: "Herramientas IA",
    language: "Español",
    theme: "Tema",
    deleteDoc: "Eliminar documento",
    search: "Vista previa",
    rotate: "Girar",
    page: "Página",
    savePdf: "Guardar PDF",
    loadingPdf: "Cargando PDF...",
    docSaved: "Documento(s) Guardado(s)",
    docSaveError: "Error al guardar documento(s)",
    openFolder: "Mostrar carpeta de destino",
    folderInfo: "Los archivos se guardan en su carpeta de Descargas predeterminada.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas",
    sortError: "Error al ordenar"
  },
  'el': {
    selectAll: "Επιλογή όλων",
    clearAll: "Καθαρισμός όλων",
    convertToPdf: "Μετατροπή σε PDF",
    saveSeparately: "Αποθήκευση ξεχωριστά",
    saveInGroup: "Αποθήκευση ως ομάδα",
    save: "Αποθήκευση",
    saving: "Αποθήκευση...",
    total: "Σύνολο",
    dragDrop: "Σύρετε ή προσθέστε",
    dropHere: "Αφήστε αρχεία εδώ",
    addFiles: "Προσθήκη αρχείων",
    edit: "Επεξεργασία",
    editorTitle: "Επεξεργαστής Εικόνας",
    pdfEditorTitle: "Επεξεργαστής PDF",
    undo: "Αναίρεση",
    redo: "Επανάληψη",
    reset: "Επαναφορά",
    cancel: "Ακύρωση",
    confirm: "Επιβεβαίωση",
    removeBg: "Αφαίρεση φόντου",
    enhance: "Βελτίωση ευκρίνειας",
    manualCrop: "Χειροκίνητη περικοπή",
    cropInstructions: "Επιλέξτε περιοχή. Η περικοπή εφαρμόζεται αυτόματα.",
    processing: "Επεξεργασία...",
    aiTools: "Εργαλεία AI",
    language: "Ελληνικά",
    theme: "Θέμα",
    deleteDoc: "Διαγραφή εγγράφου",
    search: "Προεπισκόπηση",
    rotate: "Περιστροφή",
    page: "Σελίδα",
    savePdf: "Αποθήκευση PDF",
    loadingPdf: "Φόρτωση PDF...",
    docSaved: "Το έγγραφο αποθηκεύτηκε",
    docSaveError: "Σφάλμα κατά την αποθήκευση",
    openFolder: "Εμφάνιση φακέλου προορισμού",
    folderInfo: "Τα αρχεία αποθηκεύονται στον προεπιλεγμένο φάκελο Λήψεις.",
    autoSort: "Αυτόματη ταξινόμηση",
    sorting: "Ταξινόμηση...",
    sortSuccess: "Επιτυχής ταξινόμηση",
    sortError: "Σφάλμα ταξινόμησης"
  },
  'he': {
    selectAll: "בחר הכל",
    clearAll: "נקה הכל",
    convertToPdf: "המר ל-PDF",
    saveSeparately: "שמור בנפרד",
    saveInGroup: "שמור כקבוצה",
    save: "שמור",
    saving: "שומר...",
    total: "סה״כ",
    dragDrop: "גרור או הוסף",
    dropHere: "שחרר קבצים כאן",
    addFiles: "הוסף קבצים",
    edit: "ערוך",
    editorTitle: "עורך תמונות",
    pdfEditorTitle: "עורך PDF",
    undo: "בטל",
    redo: "בצע שוב",
    reset: "אפס",
    cancel: "ביטול",
    confirm: "אשר עריכה",
    removeBg: "הסר רקע",
    enhance: "שפר חדות",
    manualCrop: "חיתוך ידני",
    cropInstructions: "בחר אזור בתמונה. החיתוך מתבצע אוטומטית בעת השחרור.",
    processing: "מעבד...",
    aiTools: "כלי AI",
    language: "עברית",
    theme: "ערכת נושא",
    deleteDoc: "מחק מסמך",
    search: "תצוגה מקדימה",
    rotate: "סובב",
    page: "עמוד",
    savePdf: "שמור PDF",
    loadingPdf: "טוען PDF...",
    docSaved: "המסמך נשמר",
    docSaveError: "שגיאה בשמירת המסמך",
    openFolder: "הצג תיקיית יעד",
    folderInfo: "הקבצים נשמרים בתיקיית ההורדות המוגדרת כברירת מחדל.",
    autoSort: "מיון אוטומטי",
    sorting: "ממיין...",
    sortSuccess: "מוין בהצלחה",
    sortError: "שגיאה במיון"
  }
};